### PR TITLE
chore: improve eslint config

### PR DESCRIPTION
**Pull request by withyellow**
1. use `eslint-define-config` for better experience.
2. force enable eslint and prettier for vscode in .vscode/settings.json.
3. `husky` + `lint-staged` might be a good choice, not sure if it's necessary. I'll raise another pr later if you think it's helpful.

### CODE REVIEW

**Comment by CaliCastle** [comment]
`husky` + `lint-staged` might be a good choice for many teams, but I personally have gone from loving them to removing them entirely.

Theo from t3.gg has done some [explanation](https://twitter.com/t3dotgg/status/1621995838615740417) on this which I think makes a lot of sense.

Why would we block ourselves from writing code just because the format or some stupid ESLint checks failed, we should ship fast and let CI do this for us. Hence, that's why I have the [workflow](https://github.com/zolplay-cn/website/blob/main/.github/workflows/prettier.yml) in place so that GitHub Actions can take care of updating the code and committing straight into the branch when needed.

**Comment by CaliCastle** [comment]
Nonetheless, thanks for caring about these toolings and contributing to the repo!

I haven't used the `eslint-define-config` yet, but I'll check it out later.

Cheers.

**Comment by withyellow** [comment]
You can also check out https://github.com/IanVS/prettier-plugin-sort-imports if you're interested, which provide import order rules.

**Comment by CaliCastle** [comment]
> You can also check out https://github.com/IanVS/prettier-plugin-sort-imports if you're interested, which provide import order rules.

We're using this plugin for our Nexus project! I just didn't include everything all at once lol, thanks!

**Review by CaliCastle — APPROVED** [review]

**Pull request merged**
